query allCharacters ($first: Int!){
  allPeople (first: $first){
    people{
      name
      
      filmConnection{films{title}}
      birthYear
      gender
      eyeColor
      hairColor
      skinColor
      height
      mass
      homeworld{name}
      species{name}
      starshipConnection{starships{name}}
      vehicleConnection{vehicles{name}}
    }
  }
}
